"""Frozen observations from the installed public 0.1.0 runtime, never regenerated by tests."""

import json
from copy import deepcopy
from hashlib import sha256
from importlib.resources import files

import pytest

from checkedflow.core.values import Failure
from checkedflow.recovery import replay_blocks
from checkedflow.serialization import decode, encode

CAPTURE_SHA256 = "04634fe3a57d6dc11a9668fa210fe964899fa07ebbc2b1899f883dc1988060c1"
FINAL_HASH = "9c12eea3393f018bbac48ad1660b1077c9e8fb6d1b6665eede9ca50cf1817950"


def capture():
    raw = files("checkedflow").joinpath("data/legacy-v1.json").read_bytes()
    assert sha256(raw).hexdigest() == CAPTURE_SHA256, "Do not rewrite historical expected values"
    return json.loads(raw)


def test_published_v1_history_preserves_every_checkpoint():
    fixture = capture()
    expected = {row["height"]: row["state_hash"] for row in fixture["checkpoints"]}
    state = decode(fixture["initial"])
    for block in fixture["blocks"]:
        runtime = replay_blocks(state, [block])
        state = runtime.state
        if block["height"] in expected:
            assert runtime.state_hash == expected[block["height"]]
    assert runtime.state_hash == FINAL_HASH == fixture["final_state_hash"]
    assert encode(state) == fixture["final_state"]
    assert state.tasks["unknown"].status == "uncertain"
    assert state.capabilities["c"].status == "revoked"
    assert state.capabilities["child"].status == "quarantined"
    assert any(residual.status == "open" for residual in state.residuals.values())
    assert state.missions["m"].spent > 0


@pytest.mark.parametrize("damage", ["gap", "outcome", "signed_payload"])
def test_legacy_history_corruption_is_rejected(damage):
    fixture = capture()
    blocks = deepcopy(fixture["blocks"][:2])
    if damage == "gap":
        blocks[1]["height"] += 1
    elif damage == "outcome":
        blocks[0]["transactions"][0]["code"] = "SIGNATURE"
    else:
        transaction = blocks[0]["transactions"][0]
        envelope = json.loads(bytes.fromhex(transaction["raw"]))
        envelope["command"]["id"] = "changed-after-signing"
        transaction["raw"] = json.dumps(envelope).encode().hex()
    with pytest.raises(Failure, match="block gap|recorded outcome differs"):
        replay_blocks(decode(fixture["initial"]), blocks)
