"""Selected invariant-breaking mutants must be killed by existing regression tests."""

import json
import os
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
MUTATIONS = [
    (
        "quorum",
        "len(ctx.signers & s.organizations.keys()) >= 3",
        "len(ctx.signers & s.organizations.keys()) >= 1",
        "test_administration_cannot_be_self_authorized",
    ),
    (
        "expiry",
        "height >= task.deadline",
        "height > task.deadline",
        "test_expiry_keeps_cost_and_requires_reconciliation",
    ),
    (
        "capacity",
        'mission.verification_reserve if task.phase != "verify" else 0',
        "0",
        "test_capacity_reserves_verification_first",
    ),
    (
        "fence",
        'task.fence == integer(p["fence"], low=1)',
        'integer(p["fence"], low=1) > 0',
        "test_expiry_keeps_cost_and_requires_reconciliation",
    ),
    (
        "dedup",
        "len(identities)",
        "len(live)",
        "test_full_lifecycle_preserves_roles_and_funded_verification",
    ),
]

OPERATIONAL_MUTATIONS = [
    (
        "observability.py",
        "test_observability.py",
        "readiness_requires_role_dependencies",
        "self.readable and all(passed for _, passed in self.checks)",
        "self.readable",
        "test_role_dependencies_are_complete_strict_and_rechecked",
    ),
    (
        "observability.py",
        "test_observability.py",
        "readiness_rechecks_freshness_after_probes",
        "            self.watchdog.current()",
        "            pass",
        "test_slow_dependency_probe_cannot_extend_node_freshness",
    ),
    (
        "replicated_artifacts.py",
        "test_replicated_artifacts.py",
        "availability_requires_three_copies",
        "len(self.verified) >= 3",
        "len(self.verified) >= 2",
        "test_publication_requires_fresh_copies_and_survives_one_loss",
    ),
    (
        "replicated_artifacts.py",
        "test_replicated_artifacts.py",
        "availability_reverifies_backend_bytes",
        "verify(ref, body)",
        "pass",
        "test_stale_forged_and_nonbinary_replies_are_reverified",
    ),
    (
        "replicated_artifacts.py",
        "test_replicated_artifacts.py",
        "publication_requires_readable_replicas",
        "        self.get(ref, access=access)",
        "        return None",
        "test_upload_acknowledgement_alone_is_not_publication",
    ),
    (
        "effect_dispatch.py",
        "test_git_staging.py",
        "staging_requires_explicit_operator_policy",
        'not staging or (stage and record["staging"] is True)',
        "True",
        "test_staging_requires_new_explicit_policy_before_reservation",
    ),
    (
        "github_drafts.py",
        "test_git_staging.py",
        "staging_rechecks_every_write",
        "                before_send(plan)\n"
        "                self._enabled(plan)\n                return obj",
        "                self._enabled(plan)\n                return obj",
        "test_every_write_rechecks_current_consensus_before_sending",
    ),
    (
        "github_drafts.py",
        "test_git_staging.py",
        "staging_binds_planned_commit",
        "head == plan.head_commit",
        "True",
        "test_different_planned_head_is_rejected_before_any_provider_access",
    ),
    (
        "effect_reconciliation.py",
        "test_effect_reconciliation.py",
        "reconciliation_binds_original_provider_policy",
        "== effect.policy",
        '!= ""',
        "test_original_approved_provider_policy_is_required",
    ),
    (
        "effect_reconciliation.py",
        "test_effect_reconciliation.py",
        "reconciliation_requires_published_bytes",
        "verify(ref, self.store.get(ref, access=self.access))",
        "pass",
        "test_publication_ack_without_readback_never_returns_proposal",
    ),
    (
        "effect_reconciliation.py",
        "test_effect_reconciliation.py",
        "reconciliation_preserves_original_object",
        "effect.number in {0, outcome.number}",
        "True",
        "test_malformed_or_changed_object_identity_is_rejected",
    ),
    (
        "worker_supervisor.py",
        "test_journal_initialization.py",
        "worker_identity_cannot_be_recreated",
        'require(not tables, "STORAGE", "missing worker identity; recovery required")',
        'require(True, "STORAGE", "missing worker identity; recovery required")',
        "test_partial_journal_never_reinitializes",
    ),
    (
        "worker_schedule.py",
        "test_journal_initialization.py",
        "missing_schedule_queue_cannot_be_recreated",
        'not tables or tables == {"schedule", "queue"}',
        "True",
        "test_partial_journal_never_reinitializes",
    ),
    (
        "sandbox_recovery.py",
        "test_journal_initialization.py",
        "sandbox_owner_cannot_be_recreated",
        'require(not tables, "STORAGE", "missing sandbox owner; recovery required")',
        'require(True, "STORAGE", "missing sandbox owner; recovery required")',
        "test_partial_journal_never_reinitializes",
    ),
    (
        "agents/journal.py",
        "test_journal_initialization.py",
        "agent_instance_cannot_be_recreated",
        "if not tables:",
        'if not self.setting("binding"):',
        "test_partial_journal_never_reinitializes",
    ),
    (
        "worker_submission.py",
        "test_worker_submission.py",
        "missing_submission_identity_never_resets_unknowns",
        'require(not tables, "STORAGE", "missing coordinator identity; recovery required")',
        'require(True, "STORAGE", "missing coordinator identity; recovery required")',
        "test_missing_coordinator_identity_never_reinitializes_unknown_work",
    ),
    (
        "effect_supervisor.py",
        "test_effect_supervisor.py",
        "effect_invocation_never_repeats_after_crash",
        'if phase == "prepared":',
        'if phase in {"prepared", "dispatching"}:',
        "test_process_exit_recovers_without_second_provider_invocation",
    ),
    (
        "effect_supervisor.py",
        "test_effect_supervisor.py",
        "effect_reservation_requires_original_coordinator_proof",
        'elif effect.status == "dispatch_reserved":',
        "elif False:",
        "test_another_reservation_cannot_fill_prepared_journal",
    ),
    (
        "effect_supervisor.py",
        "test_effect_supervisor.py",
        "effect_original_arguments_retained",
        'row[0] == binding, "BINDING", "retained effect arguments changed"',
        'True, "BINDING", "retained effect arguments changed"',
        "test_journal_argument_changes_and_cross_identity_are_rejected",
    ),
    (
        "effect_supervisor.py",
        "test_effect_supervisor.py",
        "effect_observation_publication_requires_bytes",
        "verify(ref, self.dispatcher.store.get(ref, access=self.dispatcher.access))",
        "pass",
        "test_publication_acknowledgment_without_bytes_cannot_authorize_report",
    ),
    (
        "effect_dispatch.py",
        "test_effect_dispatch.py",
        "dispatch_rechecks_current_dependencies",
        "checked = self._checked(effect, intent, contract, inputs)",
        "checked = (plan, base, patch)",
        "test_loss_during_remote_preflight_inhibits_post_and_preserves_claim",
    ),
    (
        "effect_dispatch.py",
        "test_effect_dispatch.py",
        "dispatch_rechecks_observation_inventory",
        "next(row for row in current.candidates if row.identity == candidate_id) == candidate",
        "True",
        "test_state_policy_and_freshness_rechecked_after_artifact_reads",
    ),
    (
        "github_drafts.py",
        "test_github_drafts.py",
        "effect_send_time_guard",
        "before_send(plan)",
        "pass",
        "test_final_guard_rejects_without_post_or_retry",
    ),
    (
        "github_drafts.py",
        "test_github_drafts.py",
        "effect_send_time_disable",
        "                self._enabled(plan)",
        "                pass",
        "test_final_guard_local_disable_is_rechecked",
    ),
    (
        "core/work_effects.py",
        "test_work_effects.py",
        "effect_never_resends_unknown",
        'effect.status == "authorized"',
        "True",
        "test_unknown_reservation_cannot_retry_refund_or_resume",
    ),
    (
        "core/operational.py",
        "test_work_effects.py",
        "effect_resume_requires_reconciliation",
        "effect.status in UNRESOLVED",
        "False",
        "test_unknown_reservation_cannot_retry_refund_or_resume",
    ),
    (
        "github_effects.py",
        "test_github_effects.py",
        "effect_quorum_intent_binding",
        "effect.intent == intent.digest",
        "True",
        "test_exact_reserved_plan_binds_candidate_intent_and_authorization",
    ),
    (
        "agents/tls.py",
        "test_agent_tls.py",
        "grpc_client_certificate_required",
        "require_client_auth=True",
        "require_client_auth=False",
        "test_actual_grpc_requires_certificate_token_and_current_grant",
    ),
    (
        "agents/tls.py",
        "test_agent_tls.py",
        "tls_client_certificate_required",
        "context.verify_mode = ssl.CERT_REQUIRED",
        "context.verify_mode = ssl.CERT_NONE",
        "test_http_mtls_does_not_replace_bearer_or_client_policy",
    ),
    (
        "agents/tls.py",
        "test_agent_tls.py",
        "forwarded_headers_not_authority",
        "proxy_headers=False",
        "proxy_headers=True",
        "test_forwarded_headers_cannot_override_transport",
    ),
    (
        "agents/download.py",
        "test_agent_download.py",
        "publication_reference_recheck",
        "self._load().get(fingerprint) == ref",
        "True",
        "test_read_rechecks_authority_and_provider_integrity",
    ),
    (
        "agents/download.py",
        "test_agent_download.py",
        "download_provider_integrity",
        "verify(ref, body)",
        "None",
        "test_read_rechecks_authority_and_provider_integrity",
    ),
    (
        "agents/access.py",
        "test_agent_access.py",
        "client_role_enforcement",
        'role in array(grant["roles"])',
        "True",
        "test_identity_roles_actor_scope_and_live_revocation",
    ),
    (
        "agents/access.py",
        "test_agent_access.py",
        "client_signed_actor_binding",
        'not actor or actor in array(grant["actors"])',
        "True",
        "test_identity_roles_actor_scope_and_live_revocation",
    ),
    (
        "agents/a2a.py",
        "test_agent_access.py",
        "callback_client_ownership",
        'return Principal.restore(obj(value["_principal"])).identity == owner.identity',
        "return True",
        "test_a2a_callback_ownership_and_client_bound_pagination",
    ),
    (
        "agents/http.py",
        "test_agent_access.py",
        "stream_egress_revocation",
        "                        await anyio.to_thread.run_sync(self.policy.check, principal)",
        "                        pass",
        "test_http_rechecks_policy_before_each_stream_chunk",
    ),
    (
        "agents/a2a.py",
        "test_callback_secrets.py",
        "callback_page_snapshot_revision",
        "values, revision = self.journal.configuration_snapshot(params.task_id)",
        "values = self.journal.configurations(params.task_id)\n"
        "            revision = self.journal.configuration_revision(params.task_id)",
        "test_callback_page_cursor_describes_the_returned_snapshot",
    ),
    (
        "agents/secrets.py",
        "test_callback_secrets.py",
        "callback_credentials_response_redaction",
        'authentication.pop("credentials", None)',
        "pass",
        "test_create_get_list_responses_are_redacted_but_dispatch_has_credentials",
    ),
    (
        "agents/journal.py",
        "test_callback_secrets.py",
        "callback_scope_authenticated_data",
        '"task": task,',
        '"task": "",',
        "test_rows_cannot_be_swapped_between_configurations_or_journals",
    ),
    (
        "agents/operational_gateway.py",
        "test_operational_gateway.py",
        "gateway_current_signature_and_epoch",
        "predicted_archive = Runtime(state).apply(raw, height=state.height + 1)",
        "predicted_archive = None",
        "test_bad_inputs_governance_signature_and_retired_duplicate",
    ),
    (
        "agents/operational_gateway.py",
        "test_operational_gateway.py",
        "gateway_committed_receipt_required",
        "require(confirmed(state),",
        "require(True,",
        "test_ambiguous_transport_never_retransmits",
    ),
    (
        "worker_schedule.py",
        "test_worker_schedule.py",
        "persistent_schedule_total_limit",
        "attempts >= self.policy.total_attempts",
        "False",
        "test_total_budget_and_deadline_do_not_reset",
    ),
    (
        "worker_schedule.py",
        "test_worker_schedule.py",
        "persistent_schedule_identity",
        "row[0] == binding",
        "True",
        "test_plan_binding_cannot_reset_limits",
    ),
    (
        "worker_supervisor.py",
        "test_worker_retirement.py",
        "local_recovery_capacity_before_execution",
        "exists is not None or count < MAX_LOCAL_ATTEMPTS",
        "True",
        "test_local_capacity_denies_before_lease_start_or_execution",
    ),
    (
        "worker_supervisor.py",
        "test_worker_retirement.py",
        "retained_evidence_before_buffer_retirement",
        "self._publish(state, task, evidence) == task.evidence",
        "True",
        "test_retention_failure_or_state_change_preserves_local_buffer",
    ),
    (
        "sandbox_recovery.py",
        "test_sandbox_recovery.py",
        "orphan_ownership_label",
        'and obj(obj(info["Config"])["Labels"]).get(LABEL) == token',
        "and True",
        "test_reaper_never_removes_mismatched_ownership",
    ),
    (
        "sandbox_recovery.py",
        "test_sandbox_recovery.py",
        "late_creation_intent_retention",
        "elif not record[2]:",
        "elif False:",
        "test_lost_create_reply_is_not_absence_and_late_creation_is_reaped",
    ),
    (
        "runner.py",
        "test_runner_lifecycle.py",
        "durable_container_before_start",
        "recovery.bind(name, container)",
        "pass",
        "test_execution_starts_only_an_owned_durably_bound_id",
    ),
    (
        "worker_submission.py",
        "test_worker_submission.py",
        "cached_request_current_admission",
        "Runtime(state).apply(bytes(completed), height=state.height + 1)",
        "pass",
        "test_cached_confirmation_requires_current_admission",
    ),
    (
        "worker_submission.py",
        "test_worker_submission.py",
        "worker_origin_binding",
        "not pinned or pinned == origin",
        "True",
        "test_origin_pins_identity_roots_even_when_chain_name_and_height_look_valid",
    ),
    (
        "worker_supervisor.py",
        "test_worker_supervisor.py",
        "interrupted_worker_nonrepeat",
        "if row is None and started_here:",
        "if True:",
        "test_interrupted_observer_never_runs_again",
    ),
    (
        "worker_supervisor.py",
        "test_worker_supervisor.py",
        "completion_fence_binding",
        "and task.fence == expected_fence",
        "and True",
        "test_corrupt_publisher_and_changed_completion_fence_are_rejected",
    ),
    (
        "worker_submission.py",
        "test_worker_submission.py",
        "bounded_exact_retransmission",
        "attempts < 3",
        "True",
        "test_retransmission_is_explicit_finite_and_never_resigns",
    ),
    (
        "core/work_archive.py",
        "test_work_archive.py",
        "retirement_preserves_spend",
        "ledger.archived_spent + sum(ticket.charged for ticket in removed)",
        "ledger.archived_spent",
        "test_retirement_preserves_independent_accounting",
    ),
    (
        "core/work_archive.py",
        "test_work_archive.py",
        "retirement_keeps_unknown",
        'all(ticket.status in {"settled", "released"} for ticket in removed)',
        "True",
        "test_unknown_or_reserved_funding_is_pinned",
    ),
    (
        "core/work_archive.py",
        "test_work_archive.py",
        "retirement_dependency_pin",
        "not selected_tasks.intersection(candidate.checks)",
        "True",
        "test_dependencies_expiry_and_revocation",
    ),
    (
        "operational_backup.py",
        "test_operational_backup.py",
        "application_backup_rollback",
        "checkpoint.height >= current_height",
        "True",
        "test_rollback_floor_checked_before_destination_creation",
    ),
    (
        "operational_backup.py",
        "test_operational_backup.py",
        "application_backup_replay_outcomes",
        'committed.outcomes == outcomes and committed.state_hash == row["state_hash"]',
        "True",
        "test_invalid_history_never_activates_even_with_matching_content_digest",
    ),
    (
        "dispatch_watchdog.py",
        "test_dispatch_watchdog.py",
        "stalled_height_watchdog",
        "state.height > self._warm_height",
        "state.height >= self._warm_height",
        "test_identical_successful_reads_do_not_hide_quorum_stall",
    ),
    (
        "dispatch_watchdog.py",
        "test_dispatch_watchdog.py",
        "stale_observation_watchdog",
        "now - self._sample >= self.max_age",
        "False",
        "test_cold_start_read_expiry_and_restart_require_progress",
    ),
    (
        "github_drafts.py",
        "test_github_drafts.py",
        "draft_only_observation",
        'row.get("draft") is True',
        "True",
        "test_existing_changed_or_foreign_object_cannot_be_adopted",
    ),
    (
        "github_drafts.py",
        "test_github_drafts.py",
        "draft_ci_policy",
        'policy.get("enabled") is False',
        "True",
        "test_preflight_refuses_changed_policy_or_content",
    ),
    (
        "github_drafts.py",
        "test_git_patch.py",
        "draft_patch_content_binding",
        "tree_id(result) == plan.git_tree",
        "True",
        "test_unbound_plan_rejects_before_io",
    ),
    (
        "github_drafts.py",
        "test_git_patch.py",
        "draft_base_content_binding",
        'obj(remote.get("tree")).get("sha") == tree_id(base)',
        "True",
        "test_remote_binding_failure_never_sends",
    ),
    (
        "retention_backup.py",
        "test_retention_backup.py",
        "backup_exact_digest",
        "digest.hexdigest() == checkpoint.digest",
        "True",
        "test_corrupt_or_partial_snapshot_never_activates",
    ),
    (
        "retention_backup.py",
        "test_retention_backup.py",
        "backup_current_watermark",
        "checkpoint.revision >= current_revision",
        "True",
        "test_current_floor_and_namespace_precede_input_and_filesystem_access",
    ),
    (
        "retention.py",
        "test_retention.py",
        "retention_tombstone_nonresurrection",
        'row[1] == "live"',
        "True",
        "test_tombstone_precedes_effect_and_survives_provider_resurrection",
    ),
    (
        "retention.py",
        "test_retention.py",
        "retention_plan_freshness",
        "plan.revision == revision",
        "True",
        "test_grace_pins_reopen_and_read_only_plan",
    ),
    (
        "retention.py",
        "test_retention.py",
        "retention_protected_roots",
        "row[0] + self.grace_blocks <= height and rooted is None",
        "row[0] + self.grace_blocks <= height",
        "test_forged_current_plan_cannot_erase_protected_or_young_objects",
    ),
    (
        "retention.py",
        "test_retention.py",
        "retention_restore_watermark",
        "self._meta(db)[0] >= trusted_floor",
        "True",
        "test_old_catalog_below_independent_floor_cannot_restore",
    ),
    (
        "s3_artifacts.py",
        "test_s3_artifacts.py",
        "s3_conditional_publication",
        '"If-None-Match": "*"',
        '"If-None-Match": "disabled"',
        "test_signed_conditional_publication_always_verifies_bytes",
    ),
    (
        "s3_artifacts.py",
        "test_s3_artifacts.py",
        "s3_verified_read",
        "verify(ref, body)",
        "pass",
        "test_read_hash_and_length_are_authoritative",
    ),
    (
        "repository_reuse.py",
        "test_repository_reuse.py",
        "reuse_typed_verdict_consistency",
        'report["case_match"] is expected',
        "True",
        "test_signed_pass_does_not_hide_inconsistent_evidence",
    ),
    (
        "repository_reuse.py",
        "test_repository_reuse.py",
        "reuse_provider_byte_integrity",
        "len(raw) == ref.length and digest_bytes(raw) == ref.digest",
        "True",
        "test_provider_cannot_bypass_final_byte_integrity",
    ),
    (
        "core/work_acceptance.py",
        "test_work_acceptance.py",
        "contradictory_verdict_retention",
        "len({item.task for item in candidate.observations}) != len(candidate.observations)",
        "False",
        "test_contradictory_verdict_is_retained_and_quarantines_even_without_failure",
    ),
    (
        "core/work_acceptance.py",
        "test_work_acceptance.py",
        "acceptance_organization_quorum",
        "len(organizations) >= 3",
        "len(organizations) >= 2",
        "test_three_organization_quorum_keeps_remaining_checks_and_replays",
    ),
    (
        "core/work_acceptance.py",
        "test_work_acceptance.py",
        "late_adverse_observation",
        'observation.verdict == "fail"',
        "False",
        "test_late_failure_quarantines_without_erasing_passing_quorum_or_costs",
    ),
    (
        "core/work_tasks.py",
        "test_work_tasks.py",
        "v2_attempt_fence",
        'task.fence == integer(payload["fence"], low=1)',
        'integer(payload["fence"], low=1) > 0',
        "test_competing_lease_stale_fence_and_prestart_attempt_limit",
    ),
    (
        "core/work_tasks.py",
        "test_work_tasks.py",
        "v2_lease_boundary",
        "height >= task.until",
        "height > task.until",
        "test_started_work_never_becomes_retryable_or_refundable",
    ),
    (
        "core/work_budget.py",
        "test_work_budget.py",
        "budget_spending_retention",
        "return self.archived_spent + sum(ticket.charged for ticket in self.tickets)",
        "return 0",
        "test_rejects_budget_excess_reconfiguration_and_terminal_rewriting",
    ),
    (
        "core/work_budget.py",
        "test_work_budget.py",
        "verification_budget_protection",
        "return max(0, self.verification_reserve - allocated)",
        "return 0",
        "test_verification_allocation_survives_other_phases_and_release",
    ),
    (
        "repository_execution.py",
        "test_repository_execution.py",
        "repository_inventory_binding",
        "digest_bytes(cases) == contract.test_inventory_digest",
        "True",
        "test_reject_before_sandbox",
    ),
    (
        "repository_execution.py",
        "test_repository_execution.py",
        "repository_timeout_uncertainty",
        'result.status == "reported"',
        "True",
        "test_unknown_and_mismatch_are_separate",
    ),
    (
        "vault_signer.py",
        "test_vault_signer.py",
        "managed_signer_credential_binding",
        "public_key.hex() == self.credential.public_key",
        "True",
        "test_metadata_and_signature_fail_closed",
    ),
    (
        "core/key_registry.py",
        "test_key_lifecycle.py",
        "retired_key_nonresurrection",
        "min(item.retired_height, activation)",
        "activation",
        "test_rotation_cannot_resurrect_an_expired_key_or_overlap_live_intervals",
    ),
    (
        "core/key_registry.py",
        "test_key_lifecycle.py",
        "key_possession_authority",
        "context.possession_key == public_key",
        "True",
        "test_registry_validation_and_proof_context_cannot_be_omitted",
    ),
    (
        "core/authority.py",
        "test_key_lifecycle.py",
        "key_activation_height",
        "self.activated_height <= height",
        "True",
        "test_pending_activation_retirement_and_nonce_continuity",
    ),
    (
        "artifact_io.py",
        "test_artifacts.py",
        "artifact_digest_integrity",
        "sha256(body).hexdigest() == ref.digest",
        "True",
        "test_corruption_is_detected_not_silently_repaired",
    ),
    (
        "artifact_io.py",
        "test_artifacts.py",
        "artifact_scope_authorization",
        "scope in self.scopes and permission in self.permissions",
        "True",
        "test_denial_before_storage_or_stream_observation",
    ),
    (
        "operational_storage.py",
        "test_operational_storage.py",
        "trusted_replay_checkpoint",
        "head_hash == expected_hash",
        "True",
        "test_committed_archive_reopens_and_history_replays",
    ),
    (
        "core/operational.py",
        "test_operational_runtime.py",
        "duplicate_control_application",
        "if duplicate:",
        "if False:",
        "test_replaying_an_old_pause_does_not_pause_newly_resumed_mission",
    ),
    (
        "core/request_journal.py",
        "test_request_journal.py",
        "checkpoint_nonce_continuity",
        "actors=_advance_actor(journal, command)",
        "actors=journal.actors",
        "test_ordinary_saturation_preserves_control_and_checkpoint_capacity",
    ),
    (
        "core/authority.py",
        "test_operational_identity.py",
        "organization_quorum",
        "len(organizations) >= 3",
        "len(organizations) >= 1",
        "test_three_organizations_and_purposes_are_separate",
    ),
    (
        "core/authority.py",
        "test_operational_identity.py",
        "mission_scope",
        "self.actor.mission == mission",
        "True",
        "test_worker_cannot_promote_its_role_or_mission",
    ),
    (
        "core/authority.py",
        "test_operational_identity.py",
        "key_purpose",
        "self.actor.role == role",
        "True",
        "test_worker_cannot_promote_its_role_or_mission",
    ),
    (
        "domains/repository_patch.py",
        "test_repository_patch.py",
        "patch_result_binding",
        "tree.digest == contract.result_tree",
        "True",
        "test_patch_binds_preimage_result_and_scope_without_executing",
    ),
    (
        "domains/repository_patch.py",
        "test_repository_patch.py",
        "independent_output_verdict",
        "dumps(actual) == dumps(list(expected))",
        "True",
        "test_incorrect_output_and_forged_reports_cannot_assert_success",
    ),
]


def main() -> None:
    outcomes = []
    mutations = [
        ("core/machine.py", "test_core.py", *mutation) for mutation in MUTATIONS
    ] + OPERATIONAL_MUTATIONS
    for module, suite, name, old, new, test in mutations:
        with tempfile.TemporaryDirectory(prefix="checkedflow-mutant-") as temporary:
            directory = Path(temporary)
            shutil.copytree(
                ROOT / "src/checkedflow",
                directory / "checkedflow",
                ignore=shutil.ignore_patterns("__pycache__", "proto"),
            )
            path = directory / "checkedflow" / module
            source = path.read_text()
            if old not in source:
                raise SystemExit(f"mutant no longer applies: {name}")
            path.write_text(source.replace(old, new, 1))
            environment = os.environ | {
                "PYTHONPATH": str(directory),
                "PYTHONDONTWRITEBYTECODE": "1",
            }
            result = subprocess.run(
                [
                    sys.executable,
                    "-m",
                    "pytest",
                    str(ROOT / "tests" / suite),
                    "-k",
                    test,
                    "-q",
                    "-p",
                    "no:cacheprovider",
                ],
                env=environment,
                cwd=directory,
                capture_output=True,
                timeout=120,
            )
            killed = result.returncode == 1 and b"AssertionError" in result.stdout
            # pytest.raises failures also kill admission/expiry mutants.
            killed = killed or (result.returncode == 1 and b"DID NOT RAISE" in result.stdout)
            outcomes.append({"mutant": name, "killed": killed, "test": test})
            if not killed:
                print(
                    result.stdout.decode(errors="replace"), result.stderr.decode(errors="replace")
                )
    (ROOT / "reports").mkdir(exist_ok=True)
    (ROOT / "reports/fault-injection.json").write_text(json.dumps(outcomes, indent=2))
    print(json.dumps(outcomes))
    if not all(row["killed"] for row in outcomes):
        raise SystemExit("An invariant-breaking mutation survived or failed to run.")


if __name__ == "__main__":
    main()
